// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAOB1YeJGsePdmj-pfYhbbbc7-sc-dWYU',
    appId: '1:1079606237513:web:6baf9e836f57ac0bdde298',
    messagingSenderId: '1079606237513',
    projectId: 'simple-raffle',
    authDomain: 'simple-raffle.firebaseapp.com',
    storageBucket: 'simple-raffle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjlflUF-BGd00uRkpmqncyfUsJ0We4cTU',
    appId: '1:1079606237513:android:39e1e248606b133adde298',
    messagingSenderId: '1079606237513',
    projectId: 'simple-raffle',
    storageBucket: 'simple-raffle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfYZXevnPpK3_wQPW76D_3BEeaE6nAFXI',
    appId: '1:1079606237513:ios:202d2ed538b3f822dde298',
    messagingSenderId: '1079606237513',
    projectId: 'simple-raffle',
    storageBucket: 'simple-raffle.appspot.com',
    iosClientId: '1079606237513-bcomgptf8r7mkglp70q52nlrnq419mml.apps.googleusercontent.com',
    iosBundleId: 'raffle',
  );
}
